In [6]:
import numpy as np

# NP Array

In [11]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [12]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [13]:
Lista = [1,2,3]
a2 = np.array(Lista)
a2

array([1, 2, 3])

In [14]:
Resultado = Lista * 2
Resultado

[1, 2, 3, 1, 2, 3]

In [15]:
a2 * 2

array([2, 4, 6])

# Matrices

In [18]:
matrix = numpy.array([[1,2,3],[4,5,6]]) # 2 (fila) x 3 (columna)
matrix

array([[1, 2, 3],
       [4, 5, 6]])

## Built-in functions in Numpy

In [23]:
a3 = np.arange(0, 5)
print(a3)
a4 = np.arange(0, 41, 2)
print(a4)

[0 1 2 3 4]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [32]:
zm = np.zeros([4, 5]) # 4 Filas x 5 Columnas
print(zm)
zv = np.zeros([4])
print(zv)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0. 0. 0. 0.]


In [33]:
om = np.ones([4, 5]) # 4 Filas x 5 Columnas
print(om)
ov = np.ones([4])
print(ov)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1. 1. 1. 1.]


In [35]:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Linspace

In [36]:
np.linspace(0, 3, 10)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

# Random data

In [40]:
np.random.rand(3) # uniform distribution

array([0.29430747, 0.59601225, 0.25628278])

In [41]:
np.random.randint(1, 100000, 10) # uniform distribution

array([29760, 65829, 48013, 44786, 60690, 43255, 88600,  4206, 53655,
       33457])

In [42]:
np.random.randn(2, 20) # from a normal distribution

array([[-0.76068228,  0.57330123,  1.00094937, -1.02510078, -0.89081947,
        -1.47136415, -1.28759644,  0.47160228,  1.42784882,  0.51378694,
         0.6082517 , -0.36087959, -1.36357604, -0.45148677,  2.25863074,
        -0.05930394,  0.94692876, -1.17486144, -0.53739423, -0.42541779],
       [-1.01874791, -1.00323144, -1.33639466, -1.03515165,  0.84146266,
         0.31614106, -0.64854152, -0.41125535, -1.80980825,  2.22031978,
         0.77625271, -0.11269003, -0.19248759,  2.1151092 ,  1.39330194,
         0.73078718, -0.34422412, -0.32907614,  1.12649615, -0.53496143]])

In [44]:
print(identity.shape)
print(ov.shape)

(4, 4)
(4,)


In [49]:
print(a3)
print(a3.argmax())

[0 1 2 3 4]
4


In [54]:
a5 = np.array([1,2,3,3,2,0])
print(a5.argmax()) # returns first index of max
print(a5.sum())

2
11
