#### EXERCISE



##### TASK:  get the integer part of a number with decimals

In [14]:
import numpy as np

In [15]:
arr_1 = np.random.rand(5)*100
arr_1

array([76.68259349, 40.44610054, 98.95549778, 62.83033145, 12.29785744])

### Rounding

In [16]:
arr_1.round(0)

array([77., 40., 99., 63., 12.])

### Casting to int

In [17]:
arr_1.astype(int)

array([76, 40, 98, 62, 12])

### Truncating

In [18]:
np.trunc(arr_1)

array([76., 40., 98., 62., 12.])